### ISSUE TITLE
Comparison method violates its general contract exception opening aggran file

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cbi/p2repo-aggregator#18]
With commit 6b5fe0f168c341aceb03e62ed1191fc737d258f2 of simrel I got this stack trace when using the aggran file after refreshing caches.

```java

java.lang.reflect.InvocationTargetException
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.BaseHandler$Activity.lambda$0(BaseHandler.java:183)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1233)
	at org.eclipse.emf.common.util.ECollections.sort(ECollections.java:164)
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.AnalyzeHandler$Analyzer.analyze(AnalyzeHandler.java:636)
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.AnalyzeHandler$Analyzer.perform(AnalyzeHandler.java:188)
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.BaseHandler$Activity.lambda$0(BaseHandler.java:178)
	... 1 more
Root exception:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1233)
	at org.eclipse.emf.common.util.ECollections.sort(ECollections.java:164)
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.AnalyzeHandler$Analyzer.analyze(AnalyzeHandler.java:636)
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.AnalyzeHandler$Analyzer.perform(AnalyzeHandler.java:188)
	at org.eclipse.cbi.p2repo.aggregator.analyzer.presentation.handlers.BaseHandler$Activity.lambda$0(BaseHandler.java:178)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by jonahgraham** [comment]
Probably caused by https://github.com/eclipse-simrel/simrel.build/pull/168#discussion_r1447454176

**Comment by merks** [comment]
Did you update/install the latest?

I think this is fixed by this change:

https://github.com/eclipse-cbi/p2repo-aggregator/commit/66317deee263f3bd6190230583b4afdf8a136213

**Comment by merks** [comment]
> Probably caused by [eclipse-simrel/simrel.build#168 (comment)](https://github.com/eclipse-simrel/simrel.build/pull/168#discussion_r1447454176)

No, it was caused by not comparing the correct two objects!  😱  Doh!!

**Comment by jonahgraham** [comment]
I was probably using one that predates that fix. I will try updating and reopen if I still have a problem

**Comment by jonahgraham** [comment]
BTW if it helps you diagnose for someone in the future - the latest version of the aggregator is only installing on latest platform I-build AFAICT, which meant the check for updates went "weird" for me. A new oomph setup worked, but instead of using Eclipse for Committers (which didn't work) I used Eclipse SDK (which did work)

This is the p2 error:

`
!MESSAGE Missing requirement: CBI Maven-4.0 Model for Aggregator (Experimental) 1.1.0.v20231217-1050 (org.eclipse.cbi.p2repo.aggregator.engine.maven 1.1.0.v20231217-1050) requires 'osgi.bundle; org.eclipse.equinox.p2.metadata [2.9.0,3.0.0)' but it could not be found
`
